// ai-venture-hub — minimal portfolio index (UMD: works in browser and Node)
//
// A plain index: 4 logical hub dashboards + an alphabetical list of the 54
// independent products. No suite narrative, no bundle math.
(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.HUB = factory();
})(typeof self !== "undefined" ? self : this, function () {
  var GH = "https://github.com/alexwboles/";

  var HUBS = [
    { slug: "trades-hub", name: "Trades Hub",
      blurb: "Field operations for trades: quoting, materials, permits, fleet, safety, site visits.",
      members: ["quotely-ai", "materiallist-ai", "permitpilot-ai", "fleetlog-ai", "safetycheck-ai", "sitevisit-ai"] },
    { slug: "growth-hub", name: "Growth Hub",
      blurb: "Get found, win customers, keep them: SEO, social, leads, ads, pricing, reviews, loyalty, referrals, win-back.",
      members: ["reviewpilot-ai", "socialspark-ai", "leadqualify-ai", "loyaltyloop-ai", "referralpilot-ai", "adcopy-ai", "seocheck-ai", "winback-ai", "pricingpilot-ai"] },
    { slug: "ops-hub", name: "Ops Hub",
      blurb: "The inside of the business: inbox, invoicing, cash flow, SOPs, hiring, onboarding, shifts, bookings, e-signatures.",
      members: ["triagepilot-ai", "invoicepilot-ai", "sopforge-ai", "hirewise-ai", "onboardpilot-ai", "shiftplan-ai", "cashflow-ai", "bookpilot-ai", "bizbrain-ai", "signpilot-ai"] },
    { slug: "life-hub", name: "Life Hub",
      blurb: "Household, money, health and personal goals — practical tools for real life.",
      members: ["nestlife-ai", "homekeeper-ai", "budgetlens-ai", "studyflow-ai", "menucraft-ai", "giftgenius-ai", "travelpack-ai", "roadtrip-ai", "fitnessplan-ai", "recipebox-ai", "homeinventory-ai", "gardenplan-ai", "debtpayoff-ai", "taxprep-ai", "partyplan-ai", "applypilot-ai", "habitloop-ai", "medtrack-ai", "weddingplan-ai", "babytracker-ai", "journalpilot-ai", "wardrobe-ai", "speechwriter-ai", "sidehustle-ai", "apartmenthunt-ai", "roommatesplit-ai", "movingcheck-ai", "bucketlist-ai", "hearth-ai"] }
  ];

  var PRODUCTS = [
    { slug: "adcopy-ai", name: "AdCopy AI",
      tagline: "Ad copy generator: hooks, headlines and CTAs in your brand voice." },
    { slug: "apartmenthunt-ai", name: "ApartmentHunt AI",
      tagline: "Compare apartment listings: rent, fees, commute and space side by side." },
    { slug: "applypilot-ai", name: "ApplyPilot AI",
      tagline: "Job application tracker: applications, follow-ups and interview prep in one place." },
    { slug: "babytracker-ai", name: "BabyTracker AI",
      tagline: "Baby tracker: feeds, naps, diapers and milestones logged simply." },
    { slug: "bizbrain-ai", name: "BizBrain AI",
      tagline: "Business Q&A brain: ask questions over your own business data." },
    { slug: "bookpilot-ai", name: "BookPilot AI",
      tagline: "Booking pages and appointment scheduling for service businesses." },
    { slug: "bucketlist-ai", name: "BucketList AI",
      tagline: "Bucket list planner: dream it, plan it, check it off." },
    { slug: "budgetlens-ai", name: "BudgetLens AI",
      tagline: "Upload your bank CSV. See where your money actually goes." },
    { slug: "cashflow-ai", name: "CashFlow AI",
      tagline: "Cash-flow forecaster: see what's coming in and going out." },
    { slug: "debtpayoff-ai", name: "DebtPayoff AI",
      tagline: "Debt payoff planner: avalanche vs snowball, payoff dates." },
    { slug: "fitnessplan-ai", name: "FitnessPlan AI",
      tagline: "Personal workout plans built around your goals and gear." },
    { slug: "fleetlog-ai", name: "FleetLog AI",
      tagline: "Fleet log: vehicles, maintenance and mileage for small fleets." },
    { slug: "gardenplan-ai", name: "GardenPlan AI",
      tagline: "Garden planner: what to plant, when, and where." },
    { slug: "giftgenius-ai", name: "GiftGenius AI",
      tagline: "Never panic-buy a gift again." },
    { slug: "habitloop-ai", name: "HabitLoop AI",
      tagline: "Habit tracker with streaks and gentle accountability." },
    { slug: "hearth-ai", name: "Hearth AI",
      tagline: "Chat-first personal health & home hub: meals, health, schedule, comms." },
    { slug: "hirewise-ai", name: "HireWise AI",
      tagline: "Better job posts, smarter shortlists." },
    { slug: "homeinventory-ai", name: "HomeInventory AI",
      tagline: "Home inventory: what you own, where it is, what it's worth." },
    { slug: "homekeeper-ai", name: "HomeKeeper AI",
      tagline: "Your home's maintenance schedule, handled." },
    { slug: "invoicepilot-ai", name: "InvoicePilot AI",
      tagline: "Invoices that get paid — and polite nudges when they don't." },
    { slug: "journalpilot-ai", name: "JournalPilot AI",
      tagline: "Guided journaling with prompts and reflection." },
    { slug: "leadqualify-ai", name: "LeadQualify AI",
      tagline: "A chat widget that scores your website leads while you sleep." },
    { slug: "loyaltyloop-ai", name: "LoyaltyLoop AI",
      tagline: "Loyalty program builder: points, perks and repeat buyers." },
    { slug: "materiallist-ai", name: "MaterialList AI",
      tagline: "Materials list builder: job materials with quantities and costs." },
    { slug: "medtrack-ai", name: "MedTrack AI",
      tagline: "Medication tracker: schedules, refills and adherence." },
    { slug: "menucraft-ai", name: "MenuCraft AI",
      tagline: "Menus that make mouths water — with margins that make sense." },
    { slug: "movingcheck-ai", name: "MovingCheck AI",
      tagline: "Moving checklist: timeline, tasks and box inventory." },
    { slug: "nestlife-ai", name: "NestLife AI",
      tagline: "Meals, groceries, bills and chores — one calm place." },
    { slug: "onboardpilot-ai", name: "OnboardPilot AI",
      tagline: "Employee onboarding checklists and first-week plans." },
    { slug: "partyplan-ai", name: "PartyPlan AI",
      tagline: "Party planner: guest lists, timelines and checklists." },
    { slug: "permitpilot-ai", name: "PermitPilot AI",
      tagline: "Permit tracker: applications, inspections and approvals." },
    { slug: "pricingpilot-ai", name: "PricingPilot AI",
      tagline: "Pricing calculator: costs, margins and price recommendations." },
    { slug: "quotely-ai", name: "Quotely AI",
      tagline: "Describe the job, get a professional quote in seconds." },
    { slug: "recipebox-ai", name: "RecipeBox AI",
      tagline: "Recipe box: save, organize and plan meals from your recipes." },
    { slug: "referralpilot-ai", name: "ReferralPilot AI",
      tagline: "Referral program builder: rewards that bring new customers." },
    { slug: "reviewpilot-ai", name: "ReviewPilot AI",
      tagline: "More 5-star reviews, replies written in seconds." },
    { slug: "roadtrip-ai", name: "RoadTrip AI",
      tagline: "Road trip planner: routes, stops and packing lists." },
    { slug: "roommatesplit-ai", name: "RoommateSplit AI",
      tagline: "Roommate expense splitter: bills divided fairly." },
    { slug: "safetycheck-ai", name: "SafetyCheck AI",
      tagline: "Job-site safety checklists and incident logging." },
    { slug: "seocheck-ai", name: "SEOCheck AI",
      tagline: "SEO checker: site audits and fix-it checklists." },
    { slug: "shiftplan-ai", name: "ShiftPlan AI",
      tagline: "Shift scheduler for hourly teams." },
    { slug: "sidehustle-ai", name: "SideHustle AI",
      tagline: "Side-hustle planner: ideas, pricing and launch checklists." },
    { slug: "signpilot-ai", name: "SignPilot AI",
      tagline: "E-signature request flow for documents." },
    { slug: "sitevisit-ai", name: "SiteVisit AI",
      tagline: "Site visit reports: photos, notes and follow-ups from the field." },
    { slug: "socialspark-ai", name: "SocialSpark AI",
      tagline: "One job photo → a full week of social posts." },
    { slug: "sopforge-ai", name: "SOPForge AI",
      tagline: "Plain-English description → step-by-step SOP checklist." },
    { slug: "speechwriter-ai", name: "SpeechWriter AI",
      tagline: "Speech writer: vows, toasts and talks that land." },
    { slug: "studyflow-ai", name: "StudyFlow AI",
      tagline: "Spaced-repetition exam prep that actually sticks." },
    { slug: "taxprep-ai", name: "TaxPrep AI",
      tagline: "Tax prep organizer: documents, deductions and deadlines." },
    { slug: "travelpack-ai", name: "TravelPack AI",
      tagline: "Packing lists tailored to your trip." },
    { slug: "triagepilot-ai", name: "TriagePilot AI",
      tagline: "Your inbox, sorted: urgent first, replies drafted." },
    { slug: "wardrobe-ai", name: "Wardrobe AI",
      tagline: "Wardrobe planner: outfits from what you own." },
    { slug: "weddingplan-ai", name: "WeddingPlan AI",
      tagline: "Wedding planner: budget, vendors and timelines." },
    { slug: "winback-ai", name: "WinBack AI",
      tagline: "Turn your dead customer list into revenue again." }
  ];

  function productBySlug(slug) {
    for (var i = 0; i < PRODUCTS.length; i++) if (PRODUCTS[i].slug === slug) return PRODUCTS[i];
    return null;
  }
  function repoUrl(p) { return GH + p.slug; }
  function hubUrl(h) { return GH + h.slug; }

  return { HUBS: HUBS, PRODUCTS: PRODUCTS, GH: GH,
           productBySlug: productBySlug, repoUrl: repoUrl, hubUrl: hubUrl };
});
